name: Lint check

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint-check:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@21dc36fb71dd22e3317045c0c31a3f4249868b17
        with:
          components: clippy, rustfmt
          targets: x86_64-pc-windows-msvc
          toolchain: nightly

      # Cache key is shared with the build workflow's x64 Windows target.
      - uses: swatinem/rust-cache@f0deed1e0edfc6a9be95417288c0e1099b1eeec3
        with:
          shared-key: x86_64-pc-windows-msvc-${{ hashFiles('Cargo.lock') }}

      - name: Check formatting (rustfmt)
        run: cargo fmt --check

      # Clippy itself runs `cargo check`, so this will also check for compilation errors.
      - name: Check linting (clippy)
        run: cargo clippy --all-targets --all-features -- -D warnings
